- name: rm segement data
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ declare_DATA_DIRECTORY }}"
- name: rm segement mirror data
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ declare_MIRROR_DATA_DIRECTORY }}"
  when: declare_MIRROR_DATA_DIRECTORY is defined