- name: delete hdbEnv
  file:
    path: "/usr/local/hdbEnv"
    state: "absent"
- name: ld.so.conf
  blockinfile:
    path: "/etc/ld.so.conf"
    block: "/usr/local/hdbEnv/gpos_home/lib\n\
    /usr/local/hdbEnv/gp-xerces_home/lib\n\
    /usr/local/hdbEnv/gporca_home/lib\n\
    /usr/local/hdbEnv/apr_home/lib\n\
    /usr/local/hdbEnv/apr_util_home/lib\n\
    /usr/local/hdbEnv/sigar_home/lib"
    marker: "#{mark}hdbEnv"
    state: "absent"
- name: apply ld.so.conf
  shell: "ldconfig"
