platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
outputs:
  - name: sqldump
params:
  DUMP_DB: "false"
  MAKE_TEST_COMMAND: ""
  BLDWRAP_POSTGRES_CONF_ADDONS: ""
  TEST_OS: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
run:
  path: gpdb_src/concourse/scripts/hdb_test_regress.bash
