#----检查centos防火墙
- name: check firewalld
    shell: systemctl status firewalld | grep "inactive (dead)"
    register: firewalld_result
    ignore_errors: true
- name: 
    fail:
    msg: "The firewall is not closed, which may cause communication failure between databases. Please turn off the firewall."
    when: firewalld_result.rc==1