# FILE NAME: hdbinitsystem_config

# Configuration file needed by the hdbinitsystem

################################################
#### REQUIRED PARAMETERS
################################################

#### Name of this inHybrid system enclosed in quotes.
ARRAY_NAME: "inHybrid Data Platform"

#### Naming convention for utility-generated data directories.
SEG_PREFIX: "hdbseg"

#### Base number by which primary segment port numbers 
#### are calculated.
PORT_BASE: 6000

#### File system location(s) where primary segment data directories 
#### will be created. The number of locations in the list dictate
#### the number of primary segments that will get created per
#### physical host (if multiple addresses for a host are listed in 
#### the hostfile, the number of segments will be spread evenly across
#### the specified interface addresses).
declare_DATA_DIRECTORY: ["/home/hdbadmin/hdbdata/datadir1/primary","/home/hdbadmin/hdbdata/datadir2/primary"]

#### OS-configured hostname or IP address of the master host.
MASTER_HOSTNAME: "mdw"

#### File system location where the master data directory 
#### will be created.
MASTER_DIRECTORY: "/home/hdbadmin/hdbdata/masterdir"

#### Port number for the master instance. 
MASTER_PORT: 5432

#### Shell utility used to connect to remote hosts.
TRUSTED_SHELL: "ssh"

#### Maximum log file segments between automatic WAL checkpoints.
CHECK_POINT_SEGMENTS: 8

#### Default server-side character set encoding.
ENCODING: "UNICODE"

################################################
#### OPTIONAL MIRROR PARAMETERS
################################################

#### Base number by which mirror segment port numbers 
#### are calculated.
#MIRROR_PORT_BASE: "7000"

#### File system location(s) where mirror segment data directories 
#### will be created. The number of mirror locations must equal the
#### number of primary locations as specified in the 
#### DATA_DIRECTORY parameter.
#declare_MIRROR_DATA_DIRECTORY: ["/home/hdbadmin/hdbdata/datadir1/mirror","/home/hdbadmin/hdbdata/datadir1/mirror","/home/hdbadmin/hdbdata/datadir2/mirror","/home/hdbadmin/hdbdata/datadir/mirror2"]


################################################
#### OTHER OPTIONAL PARAMETERS
################################################

#### Create a database of this name after initialization.
#DATABASE_NAME: name_of_database

#### Specify the location of the host address file here instead of
#### with the the -h option of hdbinitsystem.
MACHINE_LIST_FILE: "/home/hdbadmin/hdb_conf/hostlist"

#### This parameter specifies whether checksum is enabled for the data
#### in the heap table. When enabled, the heap storage on all databases
#### is checked, and the INHYBRID database can prevent data damage caused
#### by I / O system damage. This option is set only when the system is
#### initialized and cannot be changed later.
#### The heap check option is enabled by default, and it is strongly not
#### recommended to set it to disabled. If this option is disabled,
#### stored data corruption will not be detected and data recovery will be very difficult.
#HEAP_CHECKSUM: "on"

#### This parameter controls the information that the hdbinitsystem tool opens
#### to access IP address or host name in pg_hba.conf. The default value is 0,
#### and the tool will update the hba file with the IP address. 
#### When initializing the inHybrid database system, specify HBA_HOSTNAMES = 1
#### to have the tool update the pg_hba.conf file with the hostname.
#HBA_HOSTNAMES: 0